// <auto-generated />
using System;
using ExamBuilder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamBuilder.Migrations
{
    [DbContext(typeof(ExamBuilderContext))]
    [Migration("20260629115349_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ExamBuilder.Models.Kapitel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kapitelnummer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LehrveranstaltungId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vorlesungsfolien")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LehrveranstaltungId");

                    b.ToTable("Kapitel");
                });

            modelBuilder.Entity("ExamBuilder.Models.Lehrveranstaltung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Abschlussart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dozentenname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lehrveranstaltungen");
                });

            modelBuilder.Entity("ExamBuilder.Models.McAntwort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Antworttext")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Korrekt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("McFrageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("McFrageId");

                    b.ToTable("McAntworten");
                });

            modelBuilder.Entity("ExamBuilder.Models.McFrage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fragentext")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KapitelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KapitelId");

                    b.ToTable("McFragen");
                });

            modelBuilder.Entity("ExamBuilder.Models.Pruefung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int>("LehrveranstaltungId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LehrveranstaltungId");

                    b.ToTable("Pruefungen");
                });

            modelBuilder.Entity("McFragePruefung", b =>
                {
                    b.Property<int>("McFragenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PruefungenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("McFragenId", "PruefungenId");

                    b.HasIndex("PruefungenId");

                    b.ToTable("McFragePruefung");
                });

            modelBuilder.Entity("ExamBuilder.Models.Kapitel", b =>
                {
                    b.HasOne("ExamBuilder.Models.Lehrveranstaltung", "Lehrveranstaltung")
                        .WithMany("Kapitel")
                        .HasForeignKey("LehrveranstaltungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lehrveranstaltung");
                });

            modelBuilder.Entity("ExamBuilder.Models.McAntwort", b =>
                {
                    b.HasOne("ExamBuilder.Models.McFrage", "McFrage")
                        .WithMany("McAntworten")
                        .HasForeignKey("McFrageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("McFrage");
                });

            modelBuilder.Entity("ExamBuilder.Models.McFrage", b =>
                {
                    b.HasOne("ExamBuilder.Models.Kapitel", "Kapitel")
                        .WithMany("McFragen")
                        .HasForeignKey("KapitelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kapitel");
                });

            modelBuilder.Entity("ExamBuilder.Models.Pruefung", b =>
                {
                    b.HasOne("ExamBuilder.Models.Lehrveranstaltung", "Lehrveranstaltung")
                        .WithMany("Pruefungen")
                        .HasForeignKey("LehrveranstaltungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lehrveranstaltung");
                });

            modelBuilder.Entity("McFragePruefung", b =>
                {
                    b.HasOne("ExamBuilder.Models.McFrage", null)
                        .WithMany()
                        .HasForeignKey("McFragenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamBuilder.Models.Pruefung", null)
                        .WithMany()
                        .HasForeignKey("PruefungenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamBuilder.Models.Kapitel", b =>
                {
                    b.Navigation("McFragen");
                });

            modelBuilder.Entity("ExamBuilder.Models.Lehrveranstaltung", b =>
                {
                    b.Navigation("Kapitel");

                    b.Navigation("Pruefungen");
                });

            modelBuilder.Entity("ExamBuilder.Models.McFrage", b =>
                {
                    b.Navigation("McAntworten");
                });
#pragma warning restore 612, 618
        }
    }
}
